version: "3.7"
services: 
    database:
        container_name: db
        image: percona:5.7.34
        environment:
          MYSQL_ROOT_PASSWORD: secretpass
        restart: always
        networks:
            - basenet
    nginx:
        container_name: lb
        image: nginx:1.21.1
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports: 
            - 8080
        restart: always
        depends_on: 
            - app
        networks:
            - basenet
    app:
        build: .
        deploy:
            mode: replicated
            replicas: 2
        restart: always
        depends_on: 
            - database
        networks:
            - basenet
networks: 
    basenet: